apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-adder-deployment
  labels:
    app: csharp-adder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-adder
  template:
    metadata:
      labels:
        app: csharp-adder
    spec:
      containers:
      - name: csharp-adder
        image: ghcr.io/thwani47/csharp-adder:v2
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-adder
spec:
  selector:
    app: csharp-adder
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080