apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-divider-deployment
  labels:
    app: nestjs-divider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-divider
  template:
    metadata:
      labels:
        app: nestjs-divider
    spec:
      containers:
      - name: nestjs-divider
        image: ghcr.io/thwani47/nestjs-divider:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-divider
spec:
  selector:
    app: nestjs-divider
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 3000