version: "3"
services:
  calculator:
    image: ghcr.io/thwani47/calculator:v1
    ports:
      - "3000:80"
    depends_on:
      - csharp-adder
      - flask-multiplier
      - go-subtractor
      - nestjs-divider
  csharp-adder:
    image: ghcr.io/thwani47/csharp-adder:v1
    ports:
      - "8001:8080"
  flask-multiplier:
    image: ghcr.io/thwani47/flask-multiplier:v1
    ports:
      - "8002:5000"
  go-subtractor:
    image: ghcr.io/thwani47/go-subtractor:v1
    ports:
      - "8003:8000"
  nestjs-divider:
    image: ghcr.io/thwani47/nestjs-divider:v1
    ports:
      - "8004:3000"